title: Steven Katsaras CV
profile_img: /assets/img/profile-picture.jpg
icon_img: /assets/img/icon.webp

name: "Steven Katsaras"
job: "Senior Software Engineering Manager"
blurb: "Accomplished, enthusiastic and driven Senior Software Engineering Manager 
			with a solid history in system design, technical architecture, software 
			development and delivery. Strong and effective people leadership abilities, 
			driving high performant, cross functional teams in fast-paced, 
			competitive work environments. IT generalist that finds passion in 
			managing multiple project teams, thrives on innovating new business 
			solutions and is skilled in delivering complex software systems and 
			is committed to great customer satisfactions."

phone_number: +61 402 221 480
address: Melbourne, Australia
email: stevenkatsaras@gmail.com
linkedin_username: steven-katsaras
github_username: stevekatsaras
instagram_username: stevenkatsaras
twitter_username: Steven15386842
facebook_username:
youtube_username:
blog_url:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag